# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmH2L43yBxueX0bc7qw66QHKPE5tFtCS
"""

import tensorflow.keras
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.utils import to_categorical

(x_train,y_train),(x_test,y_test)=mnist.load_data()

x_train=x_train.reshape(60000,784)
x_test=x_test.reshape(10000,784)

print(x_train[0])

x_train=x_train/255
x_test=x_test/255

y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

model=Sequential() #線性模型

model.add(Dense(units=256,input_dim=784,activation="relu"))
model.add(Dense(units=128,activation="relu"))
model.add(Dense(units=10,activation="softmax"))

model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])

history=model.fit(x_train,y_train,batch_size=128,epochs=10,verbose=1,validation_data=(x_test,y_test))

model.summary()

